### ISSUE TITLE
Typo: compatibilty  ==> compatibility (in Pentobi-SGF.html)

### ISSUE THREAD

**Issue by jnumm** [enz/pentobi#1]
The line is 42 :)
https://github.com/enz/pentobi/blob/00e98562bba4c2e227216677f9e0d12a846afa6e/doc/blksgf/Pentobi-SGF.html#L42

This was found when I was used `check-all-the-things` to check the debian package, which in turn ran `codespell --quiet-level=3`.

**Comment by enz** [comment]
Thanks, it's now fixed.
