### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by lwchkg** [enz/pentobi#18]
This issue keeps tracks to my efforts getting Pentobi build correctly in Windows.

Here is the to-do list: (will be updated if appropriate)

- [x] ~~Get Windows build working~~ (done in #17, build instructions shown in #16)
- [x] Set up Appveyor builds
- [x] Add app icon to pentobi.exe

Windows binaries are currently placed in https://github.com/lwchkg/pentobi/releases/.

**Comment by lwchkg** [comment]
Note to self about app icon:

1. Need an .ico and an .rc file. https://doc.qt.io/qt-6/appicon.html

2. Need a way to convert svg/png to ico. We should either add an .ico to the repo or to build it dynamically with imagemagick (sadly an extra dependency). @enz I prefer adding an .ico file to the repo. Any opinion about this?

3. For the resolutions of the icon in the .ico file, we need 16x16, 32x32, 48x48 and 256x256. Maybe also 20x20, 24x24 and 28x28 for HiDPI small icons, but I need an experiment to see if they are really shown.

**Comment by lwchkg** [comment]
Windows File Explorer icon size testing result:

**Mini icon**
100% : 16px
150% : 24px
125%, 175%: 32px (no 20px or 28px)
Conclusion: prefer to use 16px icon (without padding) for all 16-32px icons. This make icons scale better.

**Others**
On 100% Windows attempt to scale down 48px icon to 40px - not nice. But removing the 48px icon is no cure - it will scale the 32px icon up instead of scale the 256px icon down.

**Final conclusion**
Create icons for 16x16, 24x24, 32x32, 48x48 and 256x256.
16x16, 24x24, 32x32: create from 16px svg (no border).
48x48: create from 48px svg.
256x256: create from 128px svg.

**Comment by enz** [comment]
I think, for now it is better to avoid the extra dependency and include a manually created ICO file into the repository.

**Comment by lwchkg** [comment]
The tasks in this issue is fixed.

enz decided to keep the AppVeyor config downstream, so if you want to check the AppVeyor config you should see my branch (lwchkg/pentobi) or send me a message.

**Comment by enz** [comment]
Could you add an issue tracker at lwchkg/pentobi such that the Windows-related bugs can be submitted and discussed there?

**Comment by lwchkg** [comment]
I have enabled the issue tracker now.
