### ISSUE TITLE
Document also dependency qtquickcontrols2-5-dev

### ISSUE THREAD

**Issue by jnumm** [enz/pentobi#3]
There are two more packages that ought to be listed in the INSTALL document: ~~qtdeclarative5-dev-tools~~ and qtquickcontrols2-5-dev. I found this out by trying to build a deb package of current snapshot in a clean Debian unstable environment (using [cowbuilder](https://wiki.debian.org/cowbuilder)).

**Comment by jnumm** [comment]
Oh, qtdeclarative5-dev actually pulls in qtdeclarative5-dev-tools, so it does not not need to be added to the list of installed packages.

I still believe that **qtquickcontrols2-5-dev** should be added to the list.

**Comment by enz** [comment]
I haven't tested it myself because I don't have a Debian-unstable installation but I am sure that you are right because I also had to add quickcontrols2 to the Qt modules in src/pentobi/Pentobi.pro when I started using a QtQuick.Controls 2 C++ class (for setting the default style in src/pentobi/Main.cpp).

I included the dependency it in INSTALL.

**Comment by jnumm** [comment]
I discovered one more: qml-module-qtwebview.

I don't have Debian unstable installed either, but I have Debian testing, and I was able to install the Qt 5.11 packages from unstable (did that a few hours ago). With this final dependency qml-module-qtwebview, I got the git version of pentobi running. That means I will be able to push Pentobi 16 to Debian pretty quickly when you release it.

**Comment by enz** [comment]
Thanks, I also added that one in INSTALL. Great to hear that you are already testing on Debian. I'm not planning to do a release before an official Ubuntu release comes with the required libraries, so hopefully after the Ubuntu 18.10 release. 

Also, there have been so many changes that Pentobi is probably full of bugs now and can use some additional time for testing. If you find any, then bug reports are very welcome (on the Github issue tracker for bugs in development versions of Pentobi)

**Comment by enz** [comment]
Now that Qt 5.11 has been pulled into the Ubuntu 18.10 development branch, I tested the compilation and found that Pentobi also needs the packages libqt5webengine5 and qml-module-qtwebengine. I added them in the INSTALL documentation, but I think that they should be automatic dependencies of libqt5webview5  and qml-module-qtwebview, so I also opened two Ubuntu bug reports [#1788832](https://bugs.launchpad.net/ubuntu/+source/qtwebview-opensource-src/+bug/1788832) and [ #1788849](https://bugs.launchpad.net/ubuntu/+source/qtwebview-opensource-src/+bug/1788849).

**Comment by jnumm** [comment]
qml-module-qtwebengine was not enough for me. I executed pentobi from terminal emulator. When pressing F1, an empty window with the title "Pentobi Help" opened up and there was this message in the console: "No WebView plug-in found!"

Installing libqt5webview5-dev resolved that and the help shows correctly, possibly because that package contains /usr/lib/x86_64-linux-gnu/qt5/plugins/webview/libqtwebview_webengine.so... but that is just a guess.

A -dev package needed for a runtime dependency seems like a problem in the Qt packaging.

**Comment by jnumm** [comment]
For the record, I reported https://bugs.debian.org/907249.

**Comment by enz** [comment]
All upstream dependency bugs have been fixed, so I am closing this issue again.
