### ISSUE TITLE
Pentobi for Android on F-Droid

### ISSUE THREAD

**Issue by comradekingu** [enz/pentobi#7]
Would be great to have Pentobi on https://f-droid.org/en/

**Comment by enz** [comment]
I already did some initial investigation how to do that, you can find more information at [issue 407](https://gitlab.com/fdroid/fdroidserver/issues/407) of the F-Droid server.

It's unlikely that I will continue to work on this in the new future, but maybe someone else is interested in creating such a package.

**Comment by enz** [comment]
After thinking about this issue again, I don't really think it falls within the scope of this project. I always liked the idea better that an open-source upstream provides the source distribution and if there is enough interest, some external contributor will pick up the task of maintaining binary packages. The only exception is currently the Android apk file available on Google Play and in the [download section](https://sourceforge.net/projects/pentobi/files/), which I maintain myself.

F-Droid has trackers where you can [request the packaging](https://gitlab.com/fdroid/rfp/issues) of new apps or [discuss issues](https://gitlab.com/fdroid/fdroiddata/issues) with existing packages.

If there is anything in the Pentobi sources that prevents the creation of a F-Droid package, or would make it easier, please open a new issue here with the specific details about the problem.
